"""Dicro pattern-aware universal compression toolkit."""

from .compressors import (
    arithmetic_decode,
    arithmetic_encode,
    bitpack_decode,
    bitpack_encode,
    bwt_decode,
    bwt_encode,
    delta_decode,
    delta_encode,
    huffman_decode,
    huffman_encode,
    lz77_decode,
    lz77_encode,
    mtf_decode,
    mtf_encode,
    rle_decode,
    rle_encode,
    xor_decode,
    xor_encode,
)
from .engine import CompressionEngine

__all__ = [
    "CompressionEngine",
    "rle_encode",
    "rle_decode",
    "delta_encode",
    "delta_decode",
    "huffman_encode",
    "huffman_decode",
    "arithmetic_encode",
    "arithmetic_decode",
    "lz77_encode",
    "lz77_decode",
    "bitpack_encode",
    "bitpack_decode",
    "xor_encode",
    "xor_decode",
    "bwt_encode",
    "bwt_decode",
    "mtf_encode",
    "mtf_decode",
]
